// Generated by CoffeeScript 1.6.2
var docpadConfig;

docpadConfig = {
  templateData: {
    site: {
      title: "Christian Fehmer"
    },
    getPreparedTitle: function() {
      if (this.document.title) {
        return "" + this.document.title + " - " + this.site.title;
      } else {
        return this.site.title;
      }
    },
    homeClass: function() {
      if (this.document.name === 'index.html') {
        return 'home';
      }
    }
  },
  collections: {
    pages: function() {
      return this.getCollection("html").findAllLive({
        isPage: true
      }, [
        {
          order: 1
        }
      ]);
    }
  }
};

module.exports = docpadConfig;
